SystemOrganization addCategory: #'Lowtalk-Core'!
SystemOrganization addCategory: 'Lowtalk-Core-AST'!
SystemOrganization addCategory: 'Lowtalk-Core-Environment'!
SystemOrganization addCategory: 'Lowtalk-Core-Exception'!
SystemOrganization addCategory: 'Lowtalk-Core-FrontEnd'!
SystemOrganization addCategory: 'Lowtalk-Core-Interpreter'!
SystemOrganization addCategory: 'Lowtalk-Core-Parser'!
SystemOrganization addCategory: 'Lowtalk-Core-Types'!
