Class {
	#name : #LowtalkInImageObjectModel,
	#superclass : #LowtalkObjectModel,
	#category : #'Lowtalk-Core-FrontEnd'
}

{ #category : #accessing }
LowtalkInImageObjectModel >> arrayClass [
	^ Array
]

{ #category : #'object creation' }
LowtalkInImageObjectModel >> convertArray: anArray [
	^ anArray
]

{ #category : #'as yet unclassified' }
LowtalkInImageObjectModel >> convertAssociation: anAssociation [
	^ anAssociation
]

{ #category : #'object creation' }
LowtalkInImageObjectModel >> convertBehavior: aBehavior [
	^ aBehavior
]

{ #category : #'object creation' }
LowtalkInImageObjectModel >> convertBoxedFloat64: aBoxedFloat64 [
	^ aBoxedFloat64
]

{ #category : #'object creation' }
LowtalkInImageObjectModel >> convertByteString: aByteString [
	^ aByteString
]

{ #category : #'object creation' }
LowtalkInImageObjectModel >> convertByteSymbol: aByteSymbol [
	^ aByteSymbol
]
